### ISSUE TITLE
`"atest"@example.com´ is parsed to `atest@example.com´

### ISSUE THREAD

**Issue by th0rb3n** [bbottema/email-rfc2822-validator#11]
Surrounding quotes (") in local part are removed when parsing to an instance of javax.mail.internet.InternetAddress. Found no EmailAddressCriteria that might avoid this behaviour.

Is it removed by intention? Removing unnecessary quotes from personal part makes sense, but dropping from local part results in a different E-Mail address.

**Comment by chconnor** [comment]
By RFC2822, "atest"@example.com and atest@example.com are in fact the "same" email address (see section 3.4.1 for the local-part specification: the quotation marks are part of the "quoted-string" token). That doesn't mean that all mail servers will obey 2822, of course. And admittedly, the spec doesn't go far in specifying the semantics. Have you tried sending to both variations to confirm that the simplified form fails?

Also, 2822 says (sec 3.4.1)

> If the string can be represented as a dot-atom (that is, it contains no characters other than atext characters or "." surrounded by atext characters), then the dot-atom form SHOULD be used and the quoted-string form SHOULD NOT be used.

**Comment by th0rb3n** [comment]
Hm... Frankly speaking, it was reported by a customer complaining that resulting E-Mail address is atest@example.org although "altest"@example.org has been entered during user provisioning.

> _Have you tried sending to both variations to confirm that the simplified form fails?_

Unfortunately, I cannot say if both addresses are effectively the same since I have o access to customer's environment.

Is there an EmailAddressCriteria that might control keeping quotes in local part?

**Comment by chconnor** [comment]
There is no EmailAddressCriteria for that, no.

Even without use of email-rfc2822-validator, I don't believe a java InternetAddress is capable of holding such an email address anyway: I don't think it allows any quoted local-part addresses at all. (Might be wrong about that.)

Usually if you want to allow incorrect/strange addresses, but still use email-rfc2822-validator, you can use email-rfc2822-validator to verify/validate addresses, but then store them without using email-rfc2822-validator to extract the address. It's not as "safe" because you have to write your own parser if you want to clean the address up in any way, but you have as much flexibility as you like, and you can still use the email-rfc2822-validator for verifying the address.

Or you could explain to the user that the two addresses are functionally identical, and that "atest"@example.com is a bad idea anyway: many (most?) mail servers will strip the quotes, or get confused. Even "proper" addresses with quoted parts, like "test\"test"@example.com will often be distorted when sent. I just sent a test message to my domain, and it was converted by my mail servers to testest@example.com before it was delivered. I suspect this is common: mail servers typically don't handle exotic 2822 addresses at all.

In the real world, most mail administrators want far more restrictive rules for their email addresses than RFC 2822 describes. This example:

 "<bob \" (here) " < (hi there) "bob(the man)smith" (hi) @ (there) example.com (hello) > (again)

...is a "valid" 2822 address, but nobody wants to allow a user to register with that. I'd recommend you tell the "atest"@example.com user that they can't have that address, and that you add a pre-check on your emails to not allow quotation marks in the local-part.

**Comment by th0rb3n** [comment]
It's a bit more complex, but I understand your point. Probably addresses are the same, but customer is simply confused because he assigned "atest" to a user, which results in atest being displayed. Thanks for taking time...
